config/routes.rb
Rails.application.routes.draw do
  resources :performs

  devise_for :users
  resources :composers do
    resources :pieces
  end
  match '/listen', to: 'halls#invite', via: 'get'
  match '/filter', to: 'halls#filter', via: 'post'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  #mount Uploader::Engine => '/uploader'
  match '/tt', to: 'composers#tt', via: 'get'
  match 'audio', to: 'audios#index', via: 'get'

  get 'contacts' => 'contacts#index', as: :contacts
  post 'contacts' => 'contacts#create', as: :create_contacts
  get 'contacts/sent' => 'contacts#sent', as: :contacts_sent

  get 'search' => 'search#index', as: :search

  resources :news, only: [:index, :show]

  root to: 'welcome#index'

  get '*slug' => 'pages#show'
  resources :pages, only: [:show]
end

app/models/composer.rb
class Composer
  include Mongoid::Document
  include Mongoid::Paperclip

  has_mongoid_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :pieces
  belongs_to :city
  field :name, type: String
  field :co_url, type: String
  field :birthday, type: Date
  field :deathday, type: Date
end

app/controllers/composers_controller.rb
class ComposersController < ApplicationController
  def new
    @composer = Composer.new
  end
  def show
    @composer = Composer.find(params[:id])
    @pieces = @composer.pieces
  end
  def create
    #@composer = Composer.create( composer_params )
    render plain: composer_params.inspect
    #if composer_pieces
    #  composer_pieces.each do |key,value|
    #    @composer.pieces.create(name: value[:name])
    #  end
    #end
    #@pieces = @composer.pieces
    #redirect_to @composer
  end
  def index
    @composers = Composer.all
  end
  def destroy
    @composer = Composer.find(params[:id])
    @composer.destroy
    redirect_to composers_path
  end
  private
  def composer_params
    params.require(:composer).permit(:avatar,:co_url,:name)
  end
  def composer_pieces
    params[:composer][:pieces_attributes]
  end
  def composer_from_url
    url = composer_params[:co_url]
    in_base = Composer.find_by(co_url: url)
    return in_base if in_base
    html = open(composer_params[:co_url]).read
    h1 = doc.at_css('div[id="vse"]')>('div[class="cnt"]')>('div[class="cat"]')>('div[class="data-case"]')>('div[class="data"]')>('h1')
    name = (h1.inner_text.split("\n")[0]).gsub(/ \z/,'')
    return Composer.new(name: name)
  end
end

app/views/composers/create.html.slim
h1
  = "Композитор #{@composer[:name]} успешно создан"
p
  = "Количество произведений #{@pieces.size}"
- if @pieces and @pieces.size > 0
  h2 с произведениями
ul
  - @composer.pieces.each do |piece|
    li
      = piece[:name]

app/views/composers/index.html.slim
h1 Composers
=link_to 'Добавить композитора', new_composer_path
-if @composers
  ul
    - @composers.each do |composer|
      li = link_to composer[:name], composer_path(composer)

app/views/composers/new.html.slim
= link_to 'Смотреть список композиторов', composers_path
= form_for @composer, :html => {:multipart => true} do |f|
  = f.label :co_url, "classic-online:"
  = f.text_field :co_url
  br
  = f.label :avatar, "Портрет"
  = f.file_field :avatar
  br
  = f.nested_fields_for :pieces do |ff|
    = ff.label :name, "Название произведения"
    = ff.text_field :name
    = ff.remove_nested_fields_link 'Исключить'
  = f.add_nested_fields_link :pieces, 'Добавить произведение'
  br
  = f.submit "Сохранить"

app/views/composers/show.html.slim
h1 
  = @composer[:name]
- if @composer.avatar
  = image_tag @composer.avatar.url(:medium)
p = link_to 'Список композиторов', composers_path
p = link_to 'Удалить', composer_path(@composer),
	    method: :delete,
	    data: {confirm: 'Are you sure?' }
- if @pieces and @pieces.size > 0
  table
    - (@composer.pieces.sort_by{|key| key[:opus]}).each do |piece|
      tr
        td = link_to piece[:name], (composer_piece_path @composer, piece)
        td = piece[:opus] if piece[:opus]

app/views/composers/tt.html.slim
map.ymap data-hint="Миллениарт" data-lat="55.752346" data-lon="37.66962" data-addr="г. Москва, ул Удальцова, д 50."